const edition = window.CONGER_EDITION;
const articles = [
{id:'sleep',topic:'睡眠与情绪',type:'原始研究 · 随机交叉试验',title:'当抑郁症的夜晚变得更深：一项慢波睡眠研究告诉了我们什么',desc:'一项随机、双盲、交叉试验，把抑郁症中的睡眠问题拆成慢波睡眠、次日警觉性和工作记忆几个可测量的问题。',question:'改善睡眠结构，能否成为理解抑郁症的新入口？',time:7},
{id:'credibility',topic:'心理治疗',type:'系统综述 · 研究可信度',title:'当“有效”还不够：一项系统综述重新检查了中国人群心理治疗试验的可信度',desc:'这篇 Lancet Psychiatry 系统综述纳入 857 项随机试验，关注随机化、分配隐藏、盲法、意向性分析和数据可信度。',question:'我们看到一个很大的治疗效应时，先应该问哪些方法学问题？',time:8}
];
const topics=['全部','睡眠与情绪','心理治疗'];
let saved=new Set(),read=new Set(),filter='全部',query='';
try{saved=new Set(JSON.parse(localStorage.getItem('conger-saved')||'[]'));read=new Set(JSON.parse(localStorage.getItem('conger-read')||'[]'))}catch{}
const app=document.getElementById('app');
const notice='<div class="notice"><span>✧</span><span>第一期已完成来源与主要结果核对。下一期论文正在候选检索和审核中。</span></div>';
function persist(){try{localStorage.setItem('conger-saved',JSON.stringify([...saved]));localStorage.setItem('conger-read',JSON.stringify([...read]));return true}catch{toast('浏览器无法保存数据，本次会话仍可使用。');return false}}
let timer;function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('show'),2400)}
function saveButton(a){return `<button class="save" data-save="${a.id}" aria-pressed="${saved.has(a.id)}" aria-label="${saved.has(a.id)?'取消收藏':'收藏'}：${a.title}">${saved.has(a.id)?'已收藏':'＋ 收藏'}</button>`}
function card(a,i){return `<article class="card"><div class="card-top"><span class="tag">${a.topic}</span><span class="card-number">0${i+1}</span></div><h3><a href="#article/${a.id}">${a.title}</a></h3><p>${a.desc}</p><div class="card-bottom"><span class="meta">约 ${a.time} 分钟 · ${read.has(a.id)?'已读':(a.type||'论文导读')}</span>${saveButton(a)}</div></article>`}
function filtered(list){return list.filter(a=>(filter==='全部'||a.topic===filter)&&(`${a.title}${a.desc}${a.topic}`.includes(query)))}
function toolbar(){return `<div class="toolbar"><div class="filters" aria-label="按专题筛选">${topics.map(t=>`<button class="filter ${filter===t?'active':''}" data-filter="${t}" aria-pressed="${filter===t}">${t}</button>`).join('')}</div><input class="search" id="search" type="search" placeholder="搜索感兴趣的问题…" aria-label="搜索论文导读"></div>`}
function cards(list){const items=filtered(list);return items.length?items.map(card).join(''):'<div class="empty"><h2>这里还没有文章</h2><p>试试其他关键词或专题，或先收藏一篇感兴趣的样稿。</p></div>'}
function listSource(){return location.hash==='#shelf'?articles.filter(a=>saved.has(a.id)):articles}
function render(){let route=location.hash.slice(1)||'home';document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route));if(document.getElementById('saved-count'))document.getElementById('saved-count').textContent=saved.size;document.title='聪儿的研究小屋';
setInterfaceLanguage(route.startsWith('english'));
if(route.startsWith('english')){renderEnglish();return}
if(route.startsWith('article/')){const a=articles.find(x=>x.id===route.split('/')[1]);if(a){renderArticle(a);return}app.innerHTML='<div class="empty"><h1>没有找到这篇文章</h1><a href="#home">回到研究小报</a></div>';return}
if(route==='shelf'){app.innerHTML=`<section class="page-title"><div class="eyebrow">YOUR LITTLE LIBRARY</div><h1>我的书架</h1><p>留住好奇，也留住下一次阅读的起点。</p><small>收藏与已读记录仅保存在当前浏览器，不会公开或跨设备同步。</small></section>${toolbar()}<div class="cards" id="cards">${cards(listSource())}</div>`}
else if(route==='topics'){app.innerHTML=`<section class="page-title"><div class="eyebrow">FOLLOW YOUR CURIOSITY</div><h1>沿着兴趣，继续探索</h1><p>从一个临床问题出发，把零散的发现连成知识。</p></section>${notice}<div class="topic-grid">${['睡眠与情绪'].map((t,i)=>`<button class="topic-card" data-topic="${t}"><span>专题 / 0${i+1}</span><strong>${t}</strong><span>${articles.some(a=>a.topic===t)?'阅读主题样稿':'内容筹备中'}</span></button>`).join('')}</div>${toolbar()}<div class="cards" id="cards">${cards(articles)}</div>`}
else{const a=articles.find(item=>item.id===edition.featuredArticleId)||articles[0];app.innerHTML=`<section class="welcome"><div><div class="eyebrow">A LITTLE ROOM FOR BIG DISCOVERIES</div><h1>${edition.headline}</h1><p>${edition.lines.join("<br>")}</p></div><div class="dog-space"><div id="dog-art" class="dog-placeholder" aria-label="陪伴阅读的小狗">🐶</div><small>${edition.companion}</small></div></section>${notice}<div class="section-head"><h2>这一期，值得慢慢读</h2><span class="issue">${edition.label}</span></div><section class="featured"><div class="feature-copy"><span class="tag">论文导读 · ${a.topic}</span><h2><a href="#article/${a.id}">${a.title}</a></h2><p>${a.desc}</p><div class="meta"><span>约 ${a.time} 分钟</span><span>论文导读</span></div><div class="feature-bottom"><a class="primary" href="#article/${a.id}">打开这篇论文导读</a>${saveButton(a)}</div></div><aside class="feature-note"><span class="label">带着一个问题阅读</span><p>“${a.question}”</p><small>从问题出发，再回到证据。</small></aside></section><div class="section-head"><h2>在这里，遇见更多问题</h2><small>不赶进度，跟着好奇心走。</small></div>${toolbar()}<div class="cards" id="cards">${cards(articles)}</div><div class="bottom-note"><strong>关于这里的每一篇文章</strong><span>正式内容将标注检索截止日期、原文依据与审核记录。证据不足时保留疑问，有待核查时暂缓发布。</span></div>`;const im=new Image();im.alt='Sophia 穿着紫色衣服与小狗一起读书的卡通形象';im.onload=()=>document.getElementById('dog-art')?.replaceWith(im);im.src='assets/conger-character-v1.png'}
const input=document.getElementById('search');if(input){input.value=query;input.addEventListener('input',e=>{query=e.target.value;document.getElementById('cards').innerHTML=cards(listSource())})}}
function renderArticle(a){document.title=a.title+' · 聪儿的研究小屋';app.innerHTML=`<article class="article"><a class="back" href="#home">返回研究小报</a><div style="margin-top:25px"><span class="tag">${a.topic} · ${a.type||'论文导读'}</span></div><h1>${a.title}</h1><p class="lead">${a.desc}</p><div class="meta"><span>约 ${a.time} 分钟</span><span>论文导读 · 结构预览</span></div><div class="article-actions">${saveButton(a)}<button class="save" data-read="${a.id}" aria-pressed="${read.has(a.id)}">${read.has(a.id)?'已读完 · 点击撤销':'标记为已读'}</button></div>${notice}<section class="summary"><div class="eyebrow">一分钟，先读这里</div><h2>先把问题问清楚</h2><p>${a.question}</p><p>本文依据期刊全文页面整理，结论范围与研究设计保持一致。</p></section><h2>01 / 为什么值得关注这个问题</h2><p>好的综述从一个具体的问题出发。我们会先交代问题的背景，区分它涉及的是病因、预测、干预效果，还是患者的长期生活质量，避免把不同问题的研究混在一起。</p><h2>02 / 把研究放在一起阅读</h2><p>这里将按照研究问题组织多篇文献，而不是逐篇翻译摘要。对每项研究，我们会记录受试人群、研究设计、对照条件、主要终点和随访时间，再比较结果是否能够放在同一框架下理解。</p><p>当研究存在分歧时，会保留分歧，并查找可能的解释。全文无法获取的文献会明确标注；摘要未提供的数字与方法不会补写。</p><h2>03 / 从研究结果回到临床问题</h2><p>正式文章会分别说明：研究结果本身是什么、作者如何解释，以及综述可以谨慎推导出什么。临床意义会结合效应大小、适用人群与不确定性讨论，不把单项发现直接转化为诊疗建议。</p><h2>04 / 把不确定性也留下来</h2><p>这里将呈现证据缺口、方法限制及仍待验证的问题。没有足够依据时，结论会收窄；存在未解决的准确性问题时，文章不会进入正式发布列表。</p><section class="review"><h2>文献与质量记录</h2><dl><dt>当前状态</dt><dd>第一期论文导读，已完成来源与主要结果核对</dd><dt>检索截止日期</dt><dd>检索截止 2026-10-01</dd><dt>文献来源</dt><dd>基于期刊全文页面与摘要，原文链接见下方</dd><dt>正式发布门槛</dt><dd>来源核实、数据核对、结论审查、分歧与局限检查已完成首轮</dd></dl></section><div class="bottom-note">每一篇认真读过的文章，都会成为理解的一小部分。</div></article>`}
document.addEventListener('click',e=>{const s=e.target.closest('[data-save]');if(s){const id=s.dataset.save;saved.has(id)?saved.delete(id):saved.add(id);const ok=persist();render();if(ok)toast(saved.has(id)?'已放进你的书架':'已从书架移除');return}const r=e.target.closest('[data-read]');if(r){read.has(r.dataset.read)?read.delete(r.dataset.read):read.add(r.dataset.read);persist();render();return}const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return}const t=e.target.closest('[data-topic]');if(t){filter=t.dataset.topic;query='';render();document.getElementById('cards').scrollIntoView({block:'start'});}});
window.addEventListener('hashchange',()=>{filter='全部';query='';render();window.scrollTo(0,0)});render();

function setInterfaceLanguage(english){
 document.documentElement.lang=english?'en':'zh-CN';
 document.querySelector('.brand').href=english?'#english':'#home';
 document.querySelector('.brand>span:last-child').innerHTML=(english?'Sophia’s English Studio':'聪儿的研究小屋')+'<small>'+(english?'READ · DISCOVER · PRACTISE':'SOPHIA’S READING ROOM')+'</small>';
 document.querySelector('nav').innerHTML=english?'<a href="#english" data-nav="english">Read</a><a href="#english/words" data-nav="english/words">Word bank</a><a href="#english/practice" data-nav="english/practice">Practice</a>':'<a href="#home" data-nav="home">研究小报</a><a href="#topics" data-nav="topics">探索专题</a><a href="#shelf" data-nav="shelf">我的书架 <span id="saved-count">'+saved.size+'</span></a>';
 document.querySelector('nav').setAttribute('aria-label',english?'English studio navigation':'主导航');
 const note=document.querySelector('.header-note');note.classList.add('area-switch');note.innerHTML=english?'<a href="#home" lang="zh-CN">返回中文研究区</a>':'<a href="#english">英语学习室 · English Studio</a>';
 document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(location.hash.slice(1)||'home')));
 document.querySelector('footer>div').innerHTML='<span class="brand-icon">✿</span> '+(english?'A little English. A new way to understand.':'为聪儿，也为每一个保持好奇的人。');
 document.querySelector('footer>span').textContent=english?'Independent lessons · Psychology in everyday English':'精神医学与心理学 · 中文研究札记';
}
