(function(){
  const TOKEN_HASH='af7c99973047a421b606881106bf63748b87a5f3106e7b6daf0a9390f389dbd2';
  const apiBase=(window.SOPHIA_SYNC_CONFIG?.apiBase||'').replace(/\/$/,'');
  const app=document.getElementById('app'), nav=document.querySelector('header'), footer=document.querySelector('footer');
  const encoder=new TextEncoder();
  async function digest(value){const bytes=await crypto.subtle.digest('SHA-256',encoder.encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');}
  function unlock(){sessionStorage.setItem('sophia-auth','ok');location.reload();}
  function showSite(){app.hidden=false;nav.hidden=false;footer.hidden=false;addLogout();window.renderSophiaApp?.();window.syncSophiaCandidateFeedback?.();}
  function addLogout(){if(document.getElementById('logout'))return;const group=document.createElement('div');group.className='header-actions';const note=nav.querySelector('.header-note');if(note)group.appendChild(note);const b=document.createElement('button');b.id='logout';b.className='save';b.textContent='退出';b.addEventListener('click',window.sophiaLogout);group.appendChild(b);nav.appendChild(group);}
  function showLogin(message=''){app.hidden=false;nav.hidden=true;footer.hidden=true;app.innerHTML=`<section class="login-shell"><div class="login-card"><div class="brand-mark">✿</div><div class="eyebrow">SOPHIA’S PRIVATE READING ROOM</div><h1>欢迎回来，聪儿。</h1><p>这是你的私人研究小屋。输入访问 token 后继续。</p><form id="token-form"><label for="access-token">Access token</label><input id="access-token" type="password" autocomplete="current-password" placeholder="输入 token" required><button class="primary" type="submit">进入研究小屋</button><span class="login-error" role="alert">${message}</span></form></div></section>`;document.getElementById('access-token').focus();document.getElementById('token-form').addEventListener('submit',async e=>{e.preventDefault();const input=document.getElementById('access-token'),error=document.querySelector('.login-error');if(apiBase){try{const response=await fetch(`${apiBase}/api/auth`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:input.value})});if(!response.ok)throw new Error('invalid token');const result=await response.json();sessionStorage.setItem('sophia-session',result.session);sessionStorage.setItem('sophia-auth','ok');location.hash=location.hash||'#home';showSite()}catch{input.value='';error.textContent='Token 不正确，或私人同步服务暂不可用。请稍后再试。'}return}if(await digest(input.value)===TOKEN_HASH){unlock();location.hash=location.hash||'#home';window.dispatchEvent(new HashChangeEvent('hashchange'));}else{input.value='';error.textContent='Token 不正确，请再试一次。';}});}
  window.sophiaLogout=()=>{const token=sessionStorage.getItem('sophia-session');if(apiBase&&token)fetch(`${apiBase}/api/logout`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}).catch(()=>{});sessionStorage.removeItem('sophia-auth');sessionStorage.removeItem('sophia-session');location.hash='#home';location.reload();};
  if(apiBase){const token=sessionStorage.getItem('sophia-session');if(token){fetch(`${apiBase}/api/session`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(!r.ok)throw new Error('expired');showSite()}).catch(()=>{sessionStorage.removeItem('sophia-auth');sessionStorage.removeItem('sophia-session');showLogin('登录状态已过期，请重新输入 token。')})}else showLogin();}
  else if(sessionStorage.getItem('sophia-auth')==='ok')showSite();else showLogin();
})();
