// Candidate briefs are based on bibliographic records and abstracts. They are not full-text reviews.
window.SOPHIA_CANDIDATES = [
  {id:'artemis-youth',pmid:'42054038',year:'2026',journal:'JAMA Psychiatry',topic:'青少年心理健康',type:'集群随机对照试验',title:'社区能否接住高风险青少年的心理求助？',paperTitle:'Adolescent Mental Health Care and Stigma: The ARTEMIS Randomized Clinical Trial',desc:'在印度 60 个社区开展的集群随机试验，把反污名宣传和基层卫生人员主导的数字识别、照护结合起来，随访 3,739 名青少年。它同时追问：改变社区态度与提供基层支持，能否让高风险青少年更容易得到帮助？',caveat:'研究场景是印度城市贫困社区，干预由社区和基层医疗体系共同实施；不能直接等同于学校心理服务或其他国家的常规诊疗。',url:'https://pubmed.ncbi.nlm.nih.gov/42054038/'},
  {id:'star-ptsd-psychosis',pmid:'42309103',year:'2026',journal:'The Lancet Psychiatry',topic:'创伤与精神病',type:'多中心务实随机试验',title:'同时面对创伤后应激和精神病症状，治疗能否两边兼顾？',paperTitle:'Trauma-focused therapy integrated with cognitive behavioural therapy for psychosis for people with post-traumatic stress disorder and psychosis (the STAR trial): a multicentre, pragmatic, randomised trial in the UK',desc:'英国 STAR 试验把创伤聚焦治疗整合进精神病认知行为治疗，比较“整合治疗加常规照护”和单独常规照护。305 名同时有 PTSD 与精神病的成人参与，研究观察 9 个月后的 PTSD 症状及其他临床结局。',caveat:'疗程长达 9 个月，治疗经过个别化；研究结论对应有专门训练团队的英国二级照护场景。',url:'https://pubmed.ncbi.nlm.nih.gov/42309103/'},
  {id:'task-shared-components',pmid:'42546730',year:'2026',journal:'The Lancet Psychiatry',topic:'心理治疗',type:'个体数据成分网络荟萃分析',title:'心理干预里，哪些“组成部分”可能真正帮得上忙？',paperTitle:'Optimising and personalising task-shared psychosocial interventions for common mental disorders',desc:'研究团队把由非专科人员提供的心理社会干预拆成具体组成部分，再比较哪些元素与症状改善相关。34 项随机试验中有 30 项提供了个体参与者数据，共 10,612 人；社会支持、行为激活和问题管理显示出较有利的信号。',caveat:'组合成分的统计估计不等于已经证明某个单独模块对每个人都有效；论文也指出族裔资料缺失，个人化预测需要谨慎解释。',url:'https://pubmed.ncbi.nlm.nih.gov/42546730/'},
  {id:'violence-nonspecialists',pmid:'42309105',year:'2026',journal:'The Lancet Psychiatry',topic:'创伤与暴力',type:'系统综述与荟萃分析',title:'经历战争或人际暴力后，非专科人员能提供哪些心理支持？',paperTitle:'Non-specialist delivered psychosocial care after war and interpersonal violence',desc:'这篇综述汇总了 45 项面向暴力经历者的随机试验，共 9,431 名成人，聚焦由受过训练但不是精神卫生专科的人员提供的心理社会干预。摘要报告焦虑、抑郁、PTSD 和功能损害平均都有改善信号。',caveat:'研究跨越多种暴力类型、国家和干预，效果并不代表所有方案相同；作者也说明没有纳入具有亲历经验者参与研究。',url:'https://pubmed.ncbi.nlm.nih.gov/42309105/'},
  {id:'prenatal-cbti-pumas',pmid:'40413907',year:'2025',journal:'Sleep Medicine',topic:'孕产期与睡眠',type:'单中心三组随机对照试验',title:'孕期失眠，线上 CBT-I 和正念睡眠方案各自带来什么？',paperTitle:'A randomized controlled trial of telemedicine CBTI and PUMAS for prenatal insomnia',desc:'64 名孕期失眠者被分到线上 CBT-I、结合正念与行为睡眠策略的 PUMAS，或睡眠卫生教育组。摘要报告两种主动治疗都改善了失眠；PUMAS 还显示对夜间认知唤醒和抑郁症状的额外信号。',caveat:'样本小、单中心，疗程和测量时间有限；这项试验不能单独确定哪类孕妇最适合哪种方案。',url:'https://pubmed.ncbi.nlm.nih.gov/40413907/'},
  {id:'prenatal-digital-mindfulness',pmid:'40324172',year:'2025',journal:'Journal of Medical Internet Research',topic:'孕产期与睡眠',type:'单盲随机对照试验',title:'手机正念课程能否帮孕妇缓解失眠？',paperTitle:'Effectiveness and Mechanisms of a Digital Mindfulness-Based Intervention for Subthreshold to Clinical Insomnia Symptoms in Pregnant Women: Randomized Controlled Trial',desc:'160 名有亚临床至临床失眠症状的孕妇参加六周数字正念项目或标准照护。研究报告孕期失眠分数有小幅改善，效果延续到孕晚期，但产后随访没有看到同样的组间获益。',caveat:'大多数结局由参与者在线自评，且项目效果没有延续到产后测量；不能据此推断长期效果。',url:'https://pubmed.ncbi.nlm.nih.gov/40324172/'},
  {id:'perinatal-digital-meta',pmid:'40816365',year:'2025',journal:'Journal of Affective Disorders',topic:'孕产期心理健康',type:'随机试验荟萃分析',title:'数字心理支持对孕产期情绪有帮助吗？诊断状态可能很关键',paperTitle:'The effect of digital health intervention on perinatal negative emotions: A meta-analysis',desc:'研究汇总 63 项随机试验，考察数字干预对孕产期恐惧、焦虑和抑郁症状的影响。摘要报告未确诊精神障碍的女性抑郁症状有改善信号；已确诊人群的抑郁结局则没有显著效果。',caveat:'纳入的干预方式和参与者差异较大；群体平均结果不能替代对已确诊患者治疗的评估。',url:'https://pubmed.ncbi.nlm.nih.gov/40816365/'},
  {id:'digital-behavioural-activation',pmid:'40526910',year:'2025',journal:'Journal of Medical Internet Research',topic:'数字心理干预',type:'系统综述与荟萃分析',title:'把行为激活搬到线上，哪些形式被真正测试过？',paperTitle:'Effectiveness of Digital Behavioral Activation Interventions for Depression and Anxiety',desc:'综述纳入 17 项随机试验，比较网络课程、电子消息提醒和远程治疗等数字行为激活方式。作者不仅看抑郁和焦虑症状，也考察生活质量、功能和压力，让“数字治疗”不只剩一个总分。',caveat:'研究包含的干预形态和人群不同，数字项目的平均结果不能自动代表某一款应用或每种服务模式。',url:'https://pubmed.ncbi.nlm.nih.gov/40526910/'},
  {id:'digital-eight-disorders',pmid:'40703853',year:'2025',journal:'Internet Interventions',topic:'数字心理干预',type:'多诊断荟萃分析',title:'同一张数字治疗地图，能覆盖八种心理障碍吗？',paperTitle:'Effectiveness of digital interventions for eight mental disorders: A meta-analytic synthesis',desc:'研究从心理治疗的持续更新数据库中整理成人已确诊抑郁、失眠、恐惧、焦虑、强迫和创伤后应激等八类障碍的数字干预试验，并按诊断汇总效果，也比较有无治疗师指导的项目。',caveat:'每类障碍纳入的试验数量、对照和指导方式不同；跨病种的合并结果不能当作统一的数字疗法效果。',url:'https://pubmed.ncbi.nlm.nih.gov/40703853/'},
  {id:'cbt-sleep-psychosis',pmid:'40401359',year:'2026',journal:'The British Journal of Psychiatry',topic:'精神病与睡眠',type:'系统综述',title:'精神病患者的睡眠问题，CBT-I 需要怎样调整？',paperTitle:'Cognitive behavioural therapy for sleep problems in psychosis: systematic review of effectiveness and acceptability',desc:'综述检索针对精神病患者或高风险人群的失眠认知行为治疗研究，也整理患者对治疗的体验、退出情况和方案改动。作者纳入 14 项研究，重点是标准 CBT-I 在这一人群里如何适配。',caveat:'纳入研究数量仍有限，方案与质量不一；摘要不能支持把某一套调整版方案视作已确立标准。',url:'https://pubmed.ncbi.nlm.nih.gov/40401359/'},
  {id:'ketamine-sleep-circadian',pmid:'42103244',year:'2026',journal:'Journal of Affective Disorders',topic:'睡眠与情绪',type:'系统综述',title:'氯胺酮与睡眠节律：它们的变化是否和抗抑郁反应有关？',paperTitle:'Effects of ketamine on sleep and circadian rhythmicity in major depressive disorder and bipolar disorder',desc:'综述纳入 26 项研究、1,694 名参与者，整理氯胺酮及相关制剂对主观睡眠、客观睡眠和昼夜节律指标的影响。摘要提示主观睡眠可能改善，也提出早期睡眠变化或许能预测部分疗效。',caveat:'客观睡眠和昼夜节律资料较少，作者把相关发现定位为初步证据；不能由此证明睡眠变化就是药物起效的原因。',url:'https://pubmed.ncbi.nlm.nih.gov/42103244/'},
  {id:'rem-nightmares',pmid:'39756154',year:'2025',journal:'Sleep Medicine',topic:'睡眠与情绪',type:'系统综述',title:'噩梦、REM 睡眠和情绪调节，是否跨越不同诊断？',paperTitle:'REM sleep, dysphoric dreams and nightmares as transdiagnostic features of psychiatric disorders with emotion dysregulation',desc:'作者从 714 条记录中纳入 28 篇研究，涉及情绪障碍、PTSD、焦虑、自闭症等人群，讨论 REM 睡眠、噩梦与情绪处理之间可能的联系。它提供了一条把睡眠问题放进跨诊断视角阅读的线索。',caveat:'综述中的研究多为观察性，不能证明 REM 睡眠变化导致情绪问题；不同诊断的人数分布也不均衡。',url:'https://pubmed.ncbi.nlm.nih.gov/39756154/'},
  {id:'bipolar2-lithium-lamotrigine',pmid:'40288449',year:'2025',journal:'Journal of Affective Disorders',topic:'双相障碍',type:'系统综述与荟萃分析',title:'双相 II 型障碍的锂盐与拉莫三嗪：试验证据有多确定？',paperTitle:'Lithium and lamotrigine for the treatment of bipolar II disorder',desc:'作者汇总 10 项随机试验、645 名双相 II 型障碍患者，比较锂盐、拉莫三嗪和安慰剂在不同病程阶段的证据。一个重要发现不是“谁胜出”，而是许多关键结局的证据确定性仍很低。',caveat:'这是证据稀少的领域，比较分析有限，作者将整体确定性评为很低；不能直接转化为个人用药选择。',url:'https://pubmed.ncbi.nlm.nih.gov/40288449/'},
  {id:'ipsrt-bipolar',pmid:'41864720',year:'2026',journal:'Archives of Psychiatric Nursing',topic:'双相障碍',type:'随机对照研究',title:'稳定日常节律的心理治疗，能否影响双相情绪波动？',paperTitle:'The effect of Interpersonal and Social Rhythm Therapy (IPSRT) applied to individuals with bipolar disorder on biological rhythms and relapses: A randomized controlled study',desc:'一项 34 人的小型随机研究观察人际与社会节律疗法后，情绪症状、生物节律和人际功能在治疗后及三个月内的变化。摘要报告多个量表出现改善信号。',caveat:'样本很小、随访仅三个月，摘要不足以判断复发预防的长期效果；需更大研究重复验证。',url:'https://pubmed.ncbi.nlm.nih.gov/41864720/'},
  {id:'ceta-ipv-hiv',pmid:'41592903',year:'2026',journal:'BMJ Mental Health',topic:'创伤与心理治疗',type:'随机试验的次要结局分析',title:'在暴力经历与 HIV 照护交织时，心理治疗带来哪些变化？',paperTitle:'Effectiveness of the Common Elements Treatment Approach for mental and behavioural health outcomes among women struggling to remain adherent to HIV treatment and who have experienced intimate partner violence in South Africa: secondary outcomes from a randomised controlled trial',desc:'南非 399 名 HIV 照护困难且有近期亲密伴侣暴力经历的女性，被随机分到由非专科人员提供的 CETA 或主动对照。本篇报告抑郁和 PTSD 等次要结局；12 个月时两项症状都显示改善差异。',caveat:'本文分析的是次要心理结局；研究对象和服务情境具体，不能把发现概括为 CETA 对所有人际暴力经历者都同样有效。',url:'https://pubmed.ncbi.nlm.nih.gov/41592903/'},
  {id:'social-determinants-prevention',pmid:'40425198',year:'2025',journal:'BMJ Mental Health',topic:'心理健康预防',type:'系统综述与荟萃分析',title:'心理预防加上社会支持，能否减少心理障碍新发？',paperTitle:'Effectiveness of combining psychological prevention interventions with interventions that address the social determinants of mental health in low- and middle-income countries: a systematic review and meta-analysis',desc:'综述 21 个中低收入国家的 31 项随机试验，共 35,885 人，检验心理预防与应对社会处境因素的干预结合后，是否减少常见心理障碍。摘要报告成人和儿童的短期抑郁、PTSD 发生风险有所下降。',caveat:'焦虑发生率缺少可用数据；较长期的获益主要见于儿童抑郁症状，干预组合不能据此视作统一方案。',url:'https://pubmed.ncbi.nlm.nih.gov/40425198/'},
  {id:'youth-depression-course',pmid:'40154950',year:'2026',journal:'Journal of the American Academy of Child & Adolescent Psychiatry',topic:'青少年心理健康',type:'系统综述与荟萃分析',title:'哪些早期线索和年轻人的抑郁反复有关？',paperTitle:'Predictors of Relapsing, Recurrent, and Chronic Depression in Young People',desc:'这篇综述整合 46 个研究、7,488 名 10–25 岁抑郁症患者，考察哪些因素与复发、反复或慢性病程有关。症状较重、功能较差和更多自杀相关想法等线索与较差病程相关。',caveat:'87% 的报告存在较高偏倚风险，整体证据确定性从很低到中等；这些是群体层面相关因素，不能单独预测某个年轻人的未来。',url:'https://pubmed.ncbi.nlm.nih.gov/40154950/'},
  {id:'psilocybin-anhedonia',pmid:'41690631',year:'2026',journal:'Journal of Affective Disorders',topic:'抑郁症治疗探索',type:'随机试验的次要分析',title:'抑郁症里的快感缺失，会跟着裸盖菇素辅助治疗改变吗？',paperTitle:'Examining the effects of psilocybin-assisted psychotherapy on anhedonia in treatment-resistant depression',desc:'研究者重新分析一项等待名单对照试验，观察 30 名难治性抑郁参与者的快感缺失变化。摘要报告两周主要时间点出现改善信号，并继续探索其与整体抑郁变化的关系。',caveat:'这是小样本研究的次要分析，不是针对快感缺失设计的独立确证试验；长期结果和因果机制仍不确定。',url:'https://pubmed.ncbi.nlm.nih.gov/41690631/'},
  {id:'sud-nonpharm-network',pmid:'42081951',year:'2026',journal:'Journal of Affective Disorders',topic:'物质使用与心理健康',type:'系统综述与网络荟萃分析',title:'物质使用障碍的非药物干预：缓解症状和改善生活质量是两回事吗？',paperTitle:'Comparative effects of non-pharmacological interventions on anxiety, depression and quality of life in individuals with substance use disorders: A systematic review and network meta-analysis',desc:'这项网络荟萃分析纳入 117 项随机试验、11,177 名参与者，比较多种非药物干预对焦虑、抑郁和生活质量的影响。摘要报告部分干预与短期症状改善相关，但生活质量证据不确定。',caveat:'网络排名受研究异质性、间接比较和头对头研究稀少影响；作者也建议结合可行性和患者偏好理解结果。',url:'https://pubmed.ncbi.nlm.nih.gov/42081951/'},
  {id:'chatbots-youth',pmid:'39935147',year:'2025',journal:'Expert Review of Medical Devices',topic:'数字心理干预',type:'随机试验荟萃分析',title:'心理健康聊天机器人，对抑郁和焦虑的证据一样吗？',paperTitle:'Effectiveness of mental health chatbots in depression and anxiety for adolescents and young adults',desc:'荟萃分析纳入 10 项面向青少年和年轻成人的随机试验，研究对象以女性和大学生为主。摘要报告抑郁症状有改善信号，但焦虑结局没有显著差异。',caveat:'样本构成偏窄，试验中的聊天机器人和对照差异较大；不能外推到所有年龄、诊断或商业聊天机器人。',url:'https://pubmed.ncbi.nlm.nih.gov/39935147/'}
];

// Plain-language notes for specialist terms shown in candidate briefs.
window.SOPHIA_CANDIDATE_GLOSSARY = {
  '集群随机试验':'不是把每个人单独抽签，而是把整所学校、社区或诊所随机分到不同方案，适合评估面向群体的干预；分析时要考虑同一群体内的人彼此相似。',
  '反污名':'减少对心理疾病的刻板印象、排斥和歧视。宣传态度改变了，不一定代表人们真的更容易获得治疗，还要看实际求助和服务使用。',
  '基层卫生人员':'在社区或基础医疗机构提供初步健康服务的工作人员，不一定受过精神科专科训练。',
  '创伤聚焦治疗':'直接围绕创伤记忆及其带来的反应开展的心理治疗；具体技术和疗程因方案而异。',
  '精神病认知行为治疗':'为有精神病性体验的人调整的认知行为治疗，通常共同理解困扰、检查解释并练习应对；不等于否定患者的体验。',
  'PTSD':'创伤后应激障碍（post-traumatic stress disorder），可能在创伤后出现侵入性回忆、回避、警觉升高等持续困扰；诊断需要专业评估。',
  '务实随机试验':'尽量在日常医疗服务里比较干预，而不是只在高度理想化的实验环境中测试；结果更贴近实施场景，但也更受当地服务条件影响。',
  '二级照护':'由专科或转诊服务提供的医疗照护；各国和地区的服务层级定义并不完全一样。',
  '任务分担':'把部分心理支持工作交给受过培训的非专科人员，在专科资源不足时扩大服务覆盖；培训、督导和转诊机制很关键。',
  '个体参与者数据':'研究者拿到每位参与者层面的原始资料，而不只是每项试验发表的汇总数字；能做更细的分析，但结论仍受原试验质量限制。',
  '成分网络荟萃分析':'把复杂干预拆成多个组成部分，再用统计模型估计哪些组合与结果相关；它不能自动证明某个单独成分就是起效原因。',
  '贝叶斯分析':'一种用统计模型把已有信息和当前数据结合起来表达不确定性的分析方法；结果依赖模型设定，仍需看假设和数据质量。',
  '非专科人员':'没有精神卫生专科资格、但经过相关训练并在督导下提供心理支持的工作人员。',
  '心理社会干预':'同时关注心理状态、人际关系和生活环境的支持或治疗；具体内容可能从心理治疗到社区支持不等。',
  'CBT-I':'失眠认知行为治疗（cognitive behavioural therapy for insomnia），用行为练习和认知策略改善失眠；不是单纯讲睡眠卫生。',
  'PUMAS':'孕期失眠项目“Perinatal Understanding of Mindful Awareness for Sleep”的简称，把正念练习与行为睡眠策略结合；仍需看具体试验如何实施。',
  '夜间认知唤醒':'睡前或夜里难以停下担忧、反复思考或保持警觉的状态；研究常用量表测量，不是单一诊断。',
  '睡眠卫生教育':'关于规律作息、环境和睡眠习惯的建议；它可以是对照或辅助内容，通常不等同于完整的失眠认知行为治疗。',
  '单盲':'研究中一类参与者或评估环节不知道分组；究竟谁被设盲要看论文，单写“单盲”并不能说明所有偏倚都已避免。',
  '亚临床':'有一些相关症状，但未必达到该研究采用的临床诊断或严重程度门槛；不代表症状不真实或不困扰。',
  '孕产期':'围绕怀孕和分娩前后的一段时期；研究对具体起止时间的定义可能不同。',
  '数字干预':'通过网站、手机应用或线上平台提供的健康支持；形式和人工支持程度差异很大，不能把所有应用当作同一种治疗。',
  '行为激活':'通过逐步安排有意义、可完成的活动，打破低落时“越难受越退缩”的循环；不是要求患者强行保持积极。',
  '诊断访谈':'由受过训练的评估者按结构化问题判断是否符合诊断标准；比只看自评分数更系统，但也不是绝对无误。',
  '治疗师指导':'项目进行时有专业人员提供反馈、提醒或支持；不同研究中指导的频率和内容可能差很多。',
  '昼夜节律':'身体大约按 24 小时循环的生理节奏，包括睡眠、体温和激素变化；光照、作息和工作安排都可能影响它。',
  '氯胺酮':'一种用于麻醉、也被研究用于快速抗抑郁治疗的药物；不同制剂、剂量、给药方式和监测条件不能混为一谈。',
  'REM 睡眠':'快速眼动睡眠阶段，常伴随生动梦境；睡眠阶段的变化与情绪有关联，但不能仅凭 REM 指标推断某人患有精神障碍。',
  '跨诊断':'不只按一种诊断来理解现象，而是研究它是否横跨多种诊断出现；跨诊断相似不表示不同疾病完全相同。',
  '情绪调节':'识别、理解并影响情绪及其表达的过程；困难可能表现为情绪很难平复或应对方式受限。',
  '双相 II 型障碍':'以抑郁发作和轻躁狂发作为主要特征的双相障碍类型；轻躁狂不等于躁狂发作，诊断需结合完整病史。',
  '锂盐':'用于双相障碍等疾病治疗的一类药物；需要医生评估适应证并进行血药浓度和身体指标监测。',
  '拉莫三嗪':'一种抗癫痫药，也用于双相障碍部分阶段的治疗；起始和加量需要遵循医疗指导，皮疹等风险需留意。',
  '证据确定性':'我们对一个研究结论有多大把握，不等于效果大小；偏倚、结果不一致、样本少等都可能降低确定性。',
  '人际与社会节律疗法':'一种用于双相障碍的心理治疗，帮助稳定日常作息节律，并处理重要人际关系；并非只靠固定作息就能替代其他治疗。',
  '生物节律':'身体内部和行为活动随时间重复变化的模式；研究中的节律量表只是其中一种测量，不代表完整生理机制。',
  'CETA':'共同要素治疗（Common Elements Treatment Approach）的简称，把多种心理治疗中常见的模块按个人问题组合；需按论文的培训、督导和实施方式理解。',
  'HIV':'人类免疫缺陷病毒；研究中的感染状况和治疗参与情况属于特定医疗背景，不能直接泛化到其他临床人群。',
  '亲密伴侣暴力':'现任或前任亲密关系中发生的身体、性或心理暴力与控制行为；讨论研究时应避免把责任归咎于受暴者。',
  '次要结局':'研究预先设定的主要问题之外，额外观察的结果；通常更适合生成线索，不能与主要结局同等看待。',
  '社会决定因素':'影响健康的社会与生活条件，例如收入、住房、教育、工作和歧视；不只是个人的心理或行为。',
  '复发':'症状缓解一段时间后再次达到疾病发作水平；不同论文对复发的定义和观察时间可能不同。',
  '慢性病程':'症状持续较长时间、未出现研究定义的充分缓解；具体时间门槛依研究而定。',
  '预后因素':'与之后病程或结局相关的特征；发现相关性不代表它造成了结局，也不能单独预测某个具体人的情况。',
  '快感缺失':'对原本可能带来愉悦的活动兴趣或愉悦体验减少，是抑郁等问题中可能出现的症状之一。',
  '裸盖菇素':'一种可产生显著意识体验变化的致幻性化合物；临床研究通常在严格筛选、监测和支持下进行，不能据此自行使用。',
  '难治性抑郁':'对既往治疗反应不足的抑郁状态；研究对“治疗次数、剂量、疗程及何为不足”的定义可能不同。',
  '次要分析':'利用原试验已有数据回答额外问题；它可能提供线索，但往往不是为验证这个额外问题而设计或统计把关。',
  '网络荟萃分析':'同时比较多种干预，既使用直接对照也使用间接比较；网络里不同研究能否公平比较是关键假设。',
  '生活质量':'患者对身体、心理和社会生活状况的综合感受，通常由量表测量；不能与症状分数完全互换。',
  '急性人群':'在研究中正处于症状明显或需要即时处理阶段的参与者；不一定代表所有长期或缓解期患者。',
  '集群随机对照试验':'以社区、学校或诊所等群体为单位，随机分配到不同方案；分析时需要考虑群体内参与者彼此相似。',
  '随机对照试验':'研究者用随机方法把参与者分到不同干预或对照组，再比较结果；随机分组能减少一些偏差，但不能保证研究其他环节都可靠。',
  '系统综述':'按预先说明的方法系统搜寻、筛选并总结相关研究；结论仍取决于纳入研究的质量和差异。',
  '荟萃分析':'用统计方法合并多项研究的结果；合并数字不代表各研究完全相同，也不会自动修复原研究的问题。',
  '随机试验':'参与者被随机分配到不同干预条件的研究；还要看对照、失访、盲法和分析是否合适。',
  '随机对照研究':'通过随机分配和对照条件来比较干预效果的研究；具体可信度要看实施与报告质量。',
  'IPSRT':'人际与社会节律疗法（interpersonal and social rhythm therapy）的简称，帮助双相障碍患者稳定日常节律并处理重要人际关系。',
  'ARTEMIS':'该论文中社区青少年心理健康干预试验的专名；具体干预是反污名宣传与基层医疗人员主导的数字支持组合，不是某一种通用疗法。',
  'STAR 试验':'该论文对创伤聚焦治疗整合进精神病认知行为治疗的试验名称；试验简称本身不代表疗法类别。',
  '安慰剂':'看起来像研究治疗、但不含该有效成分的对照；可帮助估计药物或干预本身的作用。',
  '主动对照':'对照组也接受某种服务或干预，而不是完全不处理；解释效果时要比较两组具体接受了什么。',
  '标准照护':'当地通常提供的医疗服务；不同机构和地区的实际内容可能不一样。',
  '常规照护':'当地服务体系平时提供的照护，内容会随机构、地区和时期变化。',
  '偏倚风险':'研究过程可能让结果朝某个方向偏移的程度；它提示结果需要多谨慎看，不等于研究造假。',
  '确证试验':'设计和样本规模通常更适合检验疗效是否成立的后续研究；早期小试验的积极信号仍需这类研究验证。',
  '等待名单对照':'一组先接受干预，另一组在等待一段时间后再获得干预；它与积极治疗对照回答的问题不同。',
  '间接比较':'两种干预没有在同一项试验里直接对比，而是通过各自与共同对照的结果估算差异；结论依赖可比性假设。',
  '主观睡眠':'参与者自己报告的睡眠感受或睡眠日记，不等同于脑电设备记录到的睡眠结构。',
  '客观睡眠':'通过睡眠监测设备记录的生理或行为指标；它能补充主观感受，但不一定等同于患者觉得睡得好。',
  'CBTI':'失眠认知行为治疗（cognitive behavioural therapy for insomnia）的缩写；原文题名中的写法省略了连字符。',
  'STAR trial':'这篇论文中英国多中心随机试验的名称，评估创伤聚焦治疗整合进精神病认知行为治疗的效果。',
  'systematic review':'系统综述：用事先说明的方法系统搜寻、筛选并总结相关研究。',
  'meta-analysis':'荟萃分析：用统计方法合并多项研究结果；合并结果仍受原始研究差异和质量影响。',
  'randomized controlled trial':'随机对照试验：把参与者随机分到干预组和对照组，再比较结局。',
  'randomised controlled trial':'随机对照试验：把参与者随机分到干预组和对照组，再比较结局。',
  'network meta-analysis':'网络荟萃分析：结合不同试验的直接与间接比较，同时估计多种干预的相对效果。',
  'individual participant data':'个体参与者数据：每位参与者的研究资料，而不只是论文发表的组别汇总数。',
  'component network meta-analysis':'成分网络荟萃分析：把多种干预拆为组成部分后，用统计模型估计各部分及组合与结果的关系。',
  'psychosis':'精神病性障碍或精神病性体验相关的总称；具体含义要看论文纳入标准，不能仅凭这个词推断某人的诊断。',
  'cognitive behavioural therapy':'认知行为治疗：通过共同理解想法、感受和行为之间的联系，尝试练习新的应对方式。',
  'perinatal insomnia':'孕产期失眠：围绕妊娠和分娩前后发生的失眠症状；研究对孕产期时间范围的定义可能不同。',
  'circadian rhythmicity':'昼夜节律性：接近 24 小时循环的身体节律模式，例如睡眠—清醒节律。',
  'REM sleep':'快速眼动睡眠阶段，常伴随生动梦境；阶段变化本身不能用于诊断精神疾病。',
  'Interpersonal and Social Rhythm Therapy':'人际与社会节律疗法，帮助双相障碍患者稳定作息节律并处理重要人际关系。',
  'Common Elements Treatment Approach':'共同要素治疗（CETA）：把常见心理治疗模块按个人问题组合起来的跨诊断干预。',
  'intimate partner violence':'亲密伴侣暴力：现任或前任亲密关系中发生的身体、性或心理暴力及控制行为。',
  'social determinants of mental health':'心理健康的社会决定因素：收入、住房、教育、工作和歧视等社会生活条件。',
  'anhedonia':'快感缺失：对原本可能带来愉悦的活动兴趣或愉悦体验减少。',
  'treatment-resistant depression':'难治性抑郁：对既往治疗反应不足的抑郁状态；论文间的定义不一定相同。',
  'psilocybin':'裸盖菇素：可产生显著意识体验变化的致幻性化合物；临床研究在严格筛选、监测和支持下开展。',
  'substance use disorders':'物质使用障碍：与酒精或其他物质使用相关、造成明显健康或生活损害的一组诊断。',
  'mental health chatbots':'心理健康聊天机器人：以对话方式提供心理健康信息或支持的数字工具；不同工具的安全性、内容和证据差异很大。'
};
