// Candidate briefs are based on bibliographic records and abstracts. They are not full-text reviews.
window.SOPHIA_CANDIDATES = [
  {id:'artemis-youth',pmid:'42054038',year:'2026',journal:'JAMA Psychiatry',topic:'青少年心理健康',type:'集群随机对照试验',title:'社区能否接住高风险青少年的心理求助？',paperTitle:'Adolescent Mental Health Care and Stigma: The ARTEMIS Randomized Clinical Trial',desc:'在印度 60 个社区开展的集群随机试验，把反污名宣传和基层卫生人员主导的数字识别、照护结合起来，随访 3,739 名青少年。它同时追问：改变社区态度与提供基层支持，能否让高风险青少年更容易得到帮助？',caveat:'研究场景是印度城市贫困社区，干预由社区和基层医疗体系共同实施；不能直接等同于学校心理服务或其他国家的常规诊疗。',url:'https://pubmed.ncbi.nlm.nih.gov/42054038/'},
  {id:'star-ptsd-psychosis',pmid:'42309103',year:'2026',journal:'The Lancet Psychiatry',topic:'创伤与精神病',type:'多中心务实随机试验',title:'同时面对创伤后应激和精神病症状，治疗能否两边兼顾？',paperTitle:'Trauma-focused therapy integrated with cognitive behavioural therapy for psychosis for people with post-traumatic stress disorder and psychosis (the STAR trial): a multicentre, pragmatic, randomised trial in the UK',desc:'英国 STAR 试验把创伤聚焦治疗整合进精神病认知行为治疗，比较“整合治疗加常规照护”和单独常规照护。305 名同时有 PTSD 与精神病的成人参与，研究观察 9 个月后的 PTSD 症状及其他临床结局。',caveat:'疗程长达 9 个月，治疗经过个别化；研究结论对应有专门训练团队的英国二级照护场景。',url:'https://pubmed.ncbi.nlm.nih.gov/42309103/'},
  {id:'task-shared-components',pmid:'42546730',year:'2026',journal:'The Lancet Psychiatry',topic:'心理治疗',type:'个体数据成分网络荟萃分析',title:'心理干预里，哪些“组成部分”可能真正帮得上忙？',paperTitle:'Optimising and personalising task-shared psychosocial interventions for common mental disorders',desc:'研究团队把由非专科人员提供的心理社会干预拆成具体组成部分，再比较哪些元素与症状改善相关。34 项随机试验中有 30 项提供了个体参与者数据，共 10,612 人；社会支持、行为激活和问题管理显示出较有利的信号。',caveat:'组合成分的统计估计不等于已经证明某个单独模块对每个人都有效；论文也指出族裔资料缺失，个人化预测需要谨慎解释。',url:'https://pubmed.ncbi.nlm.nih.gov/42546730/'},
  {id:'violence-nonspecialists',pmid:'42309105',year:'2026',journal:'The Lancet Psychiatry',topic:'创伤与暴力',type:'系统综述与荟萃分析',title:'经历战争或人际暴力后，非专科人员能提供哪些心理支持？',paperTitle:'Non-specialist delivered psychosocial care after war and interpersonal violence',desc:'这篇综述汇总了 45 项面向暴力经历者的随机试验，共 9,431 名成人，聚焦由受过训练但不是精神卫生专科的人员提供的心理社会干预。摘要报告焦虑、抑郁、PTSD 和功能损害平均都有改善信号。',caveat:'研究跨越多种暴力类型、国家和干预，效果并不代表所有方案相同；作者也说明没有纳入具有亲历经验者参与研究。',url:'https://pubmed.ncbi.nlm.nih.gov/42309105/'},
  {id:'prenatal-cbti-pumas',pmid:'40413907',year:'2025',journal:'Sleep Medicine',topic:'孕产期与睡眠',type:'单中心三组随机对照试验',title:'孕期失眠，线上 CBT-I 和正念睡眠方案各自带来什么？',paperTitle:'A randomized controlled trial of telemedicine CBTI and PUMAS for prenatal insomnia',desc:'64 名孕期失眠者被分到线上 CBT-I、结合正念与行为睡眠策略的 PUMAS，或睡眠卫生教育组。摘要报告两种主动治疗都改善了失眠；PUMAS 还显示对夜间认知唤醒和抑郁症状的额外信号。',caveat:'样本小、单中心，疗程和测量时间有限；这项试验不能单独确定哪类孕妇最适合哪种方案。',url:'https://pubmed.ncbi.nlm.nih.gov/40413907/'},
  {id:'prenatal-digital-mindfulness',pmid:'40324172',year:'2025',journal:'Journal of Medical Internet Research',topic:'孕产期与睡眠',type:'单盲随机对照试验',title:'手机正念课程能否帮孕妇缓解失眠？',paperTitle:'Effectiveness and Mechanisms of a Digital Mindfulness-Based Intervention for Subthreshold to Clinical Insomnia Symptoms in Pregnant Women: Randomized Controlled Trial',desc:'160 名有亚临床至临床失眠症状的孕妇参加六周数字正念项目或标准照护。研究报告孕期失眠分数有小幅改善，效果延续到孕晚期，但产后随访没有看到同样的组间获益。',caveat:'大多数结局由参与者在线自评，且项目效果没有延续到产后测量；不能据此推断长期效果。',url:'https://pubmed.ncbi.nlm.nih.gov/40324172/'},
  {id:'perinatal-digital-meta',pmid:'40816365',year:'2025',journal:'Journal of Affective Disorders',topic:'孕产期心理健康',type:'随机试验荟萃分析',title:'数字心理支持对孕产期情绪有帮助吗？诊断状态可能很关键',paperTitle:'The effect of digital health intervention on perinatal negative emotions: A meta-analysis',desc:'研究汇总 63 项随机试验，考察数字干预对孕产期恐惧、焦虑和抑郁症状的影响。摘要报告未确诊精神障碍的女性抑郁症状有改善信号；已确诊人群的抑郁结局则没有显著效果。',caveat:'纳入的干预方式和参与者差异较大；群体平均结果不能替代对已确诊患者治疗的评估。',url:'https://pubmed.ncbi.nlm.nih.gov/40816365/'},
  {id:'digital-behavioural-activation',pmid:'40526910',year:'2025',journal:'Journal of Medical Internet Research',topic:'数字心理干预',type:'系统综述与荟萃分析',title:'把行为激活搬到线上，哪些形式被真正测试过？',paperTitle:'Effectiveness of Digital Behavioral Activation Interventions for Depression and Anxiety',desc:'综述纳入 17 项随机试验，比较网络课程、电子消息提醒和远程治疗等数字行为激活方式。作者不仅看抑郁和焦虑症状，也考察生活质量、功能和压力，让“数字治疗”不只剩一个总分。',caveat:'研究包含的干预形态和人群不同，数字项目的平均结果不能自动代表某一款应用或每种服务模式。',url:'https://pubmed.ncbi.nlm.nih.gov/40526910/'},
  {id:'digital-eight-disorders',pmid:'40703853',year:'2025',journal:'Internet Interventions',topic:'数字心理干预',type:'多诊断荟萃分析',title:'同一张数字治疗地图，能覆盖八种心理障碍吗？',paperTitle:'Effectiveness of digital interventions for eight mental disorders: A meta-analytic synthesis',desc:'研究从心理治疗的持续更新数据库中整理成人已确诊抑郁、失眠、恐惧、焦虑、强迫和创伤后应激等八类障碍的数字干预试验，并按诊断汇总效果，也比较有无治疗师指导的项目。',caveat:'每类障碍纳入的试验数量、对照和指导方式不同；跨病种的合并结果不能当作统一的数字疗法效果。',url:'https://pubmed.ncbi.nlm.nih.gov/40703853/'},
  {id:'cbt-sleep-psychosis',pmid:'40401359',year:'2026',journal:'The British Journal of Psychiatry',topic:'精神病与睡眠',type:'系统综述',title:'精神病患者的睡眠问题，CBT-I 需要怎样调整？',paperTitle:'Cognitive behavioural therapy for sleep problems in psychosis: systematic review of effectiveness and acceptability',desc:'综述检索针对精神病患者或高风险人群的失眠认知行为治疗研究，也整理患者对治疗的体验、退出情况和方案改动。作者纳入 14 项研究，重点是标准 CBT-I 在这一人群里如何适配。',caveat:'纳入研究数量仍有限，方案与质量不一；摘要不能支持把某一套调整版方案视作已确立标准。',url:'https://pubmed.ncbi.nlm.nih.gov/40401359/'},
  {id:'ketamine-sleep-circadian',pmid:'42103244',year:'2026',journal:'Journal of Affective Disorders',topic:'睡眠与情绪',type:'系统综述',title:'氯胺酮与睡眠节律：它们的变化是否和抗抑郁反应有关？',paperTitle:'Effects of ketamine on sleep and circadian rhythmicity in major depressive disorder and bipolar disorder',desc:'综述纳入 26 项研究、1,694 名参与者，整理氯胺酮及相关制剂对主观睡眠、客观睡眠和昼夜节律指标的影响。摘要提示主观睡眠可能改善，也提出早期睡眠变化或许能预测部分疗效。',caveat:'客观睡眠和昼夜节律资料较少，作者把相关发现定位为初步证据；不能由此证明睡眠变化就是药物起效的原因。',url:'https://pubmed.ncbi.nlm.nih.gov/42103244/'},
  {id:'rem-nightmares',pmid:'39756154',year:'2025',journal:'Sleep Medicine',topic:'睡眠与情绪',type:'系统综述',title:'噩梦、REM 睡眠和情绪调节，是否跨越不同诊断？',paperTitle:'REM sleep, dysphoric dreams and nightmares as transdiagnostic features of psychiatric disorders with emotion dysregulation',desc:'作者从 714 条记录中纳入 28 篇研究，涉及情绪障碍、PTSD、焦虑、自闭症等人群，讨论 REM 睡眠、噩梦与情绪处理之间可能的联系。它提供了一条把睡眠问题放进跨诊断视角阅读的线索。',caveat:'综述中的研究多为观察性，不能证明 REM 睡眠变化导致情绪问题；不同诊断的人数分布也不均衡。',url:'https://pubmed.ncbi.nlm.nih.gov/39756154/'},
  {id:'bipolar2-lithium-lamotrigine',pmid:'40288449',year:'2025',journal:'Journal of Affective Disorders',topic:'双相障碍',type:'系统综述与荟萃分析',title:'双相 II 型障碍的锂盐与拉莫三嗪：试验证据有多确定？',paperTitle:'Lithium and lamotrigine for the treatment of bipolar II disorder',desc:'作者汇总 10 项随机试验、645 名双相 II 型障碍患者，比较锂盐、拉莫三嗪和安慰剂在不同病程阶段的证据。一个重要发现不是“谁胜出”，而是许多关键结局的证据确定性仍很低。',caveat:'这是证据稀少的领域，比较分析有限，作者将整体确定性评为很低；不能直接转化为个人用药选择。',url:'https://pubmed.ncbi.nlm.nih.gov/40288449/'},
  {id:'ipsrt-bipolar',pmid:'41864720',year:'2026',journal:'Archives of Psychiatric Nursing',topic:'双相障碍',type:'随机对照研究',title:'稳定日常节律的心理治疗，能否影响双相情绪波动？',paperTitle:'The effect of Interpersonal and Social Rhythm Therapy (IPSRT) applied to individuals with bipolar disorder on biological rhythms and relapses: A randomized controlled study',desc:'一项 34 人的小型随机研究观察人际与社会节律疗法后，情绪症状、生物节律和人际功能在治疗后及三个月内的变化。摘要报告多个量表出现改善信号。',caveat:'样本很小、随访仅三个月，摘要不足以判断复发预防的长期效果；需更大研究重复验证。',url:'https://pubmed.ncbi.nlm.nih.gov/41864720/'},
  {id:'ceta-ipv-hiv',pmid:'41592903',year:'2026',journal:'BMJ Mental Health',topic:'创伤与心理治疗',type:'随机试验的次要结局分析',title:'在暴力经历与 HIV 照护交织时，心理治疗带来哪些变化？',paperTitle:'Effectiveness of the Common Elements Treatment Approach for mental and behavioural health outcomes among women struggling to remain adherent to HIV treatment and who have experienced intimate partner violence in South Africa: secondary outcomes from a randomised controlled trial',desc:'南非 399 名 HIV 照护困难且有近期亲密伴侣暴力经历的女性，被随机分到由非专科人员提供的 CETA 或主动对照。本篇报告抑郁和 PTSD 等次要结局；12 个月时两项症状都显示改善差异。',caveat:'本文分析的是次要心理结局；研究对象和服务情境具体，不能把发现概括为 CETA 对所有人际暴力经历者都同样有效。',url:'https://pubmed.ncbi.nlm.nih.gov/41592903/'},
  {id:'social-determinants-prevention',pmid:'40425198',year:'2025',journal:'BMJ Mental Health',topic:'心理健康预防',type:'系统综述与荟萃分析',title:'心理预防加上社会支持，能否减少心理障碍新发？',paperTitle:'Effectiveness of combining psychological prevention interventions with interventions that address the social determinants of mental health in low- and middle-income countries: a systematic review and meta-analysis',desc:'综述 21 个中低收入国家的 31 项随机试验，共 35,885 人，检验心理预防与应对社会处境因素的干预结合后，是否减少常见心理障碍。摘要报告成人和儿童的短期抑郁、PTSD 发生风险有所下降。',caveat:'焦虑发生率缺少可用数据；较长期的获益主要见于儿童抑郁症状，干预组合不能据此视作统一方案。',url:'https://pubmed.ncbi.nlm.nih.gov/40425198/'},
  {id:'youth-depression-course',pmid:'40154950',year:'2026',journal:'Journal of the American Academy of Child & Adolescent Psychiatry',topic:'青少年心理健康',type:'系统综述与荟萃分析',title:'哪些早期线索和年轻人的抑郁反复有关？',paperTitle:'Predictors of Relapsing, Recurrent, and Chronic Depression in Young People',desc:'这篇综述整合 46 个研究、7,488 名 10–25 岁抑郁症患者，考察哪些因素与复发、反复或慢性病程有关。症状较重、功能较差和更多自杀相关想法等线索与较差病程相关。',caveat:'87% 的报告存在较高偏倚风险，整体证据确定性从很低到中等；这些是群体层面相关因素，不能单独预测某个年轻人的未来。',url:'https://pubmed.ncbi.nlm.nih.gov/40154950/'},
  {id:'psilocybin-anhedonia',pmid:'41690631',year:'2026',journal:'Journal of Affective Disorders',topic:'抑郁症治疗探索',type:'随机试验的次要分析',title:'抑郁症里的快感缺失，会跟着裸盖菇素辅助治疗改变吗？',paperTitle:'Examining the effects of psilocybin-assisted psychotherapy on anhedonia in treatment-resistant depression',desc:'研究者重新分析一项等待名单对照试验，观察 30 名难治性抑郁参与者的快感缺失变化。摘要报告两周主要时间点出现改善信号，并继续探索其与整体抑郁变化的关系。',caveat:'这是小样本研究的次要分析，不是针对快感缺失设计的独立确证试验；长期结果和因果机制仍不确定。',url:'https://pubmed.ncbi.nlm.nih.gov/41690631/'},
  {id:'sud-nonpharm-network',pmid:'42081951',year:'2026',journal:'Journal of Affective Disorders',topic:'物质使用与心理健康',type:'系统综述与网络荟萃分析',title:'物质使用障碍的非药物干预：缓解症状和改善生活质量是两回事吗？',paperTitle:'Comparative effects of non-pharmacological interventions on anxiety, depression and quality of life in individuals with substance use disorders: A systematic review and network meta-analysis',desc:'这项网络荟萃分析纳入 117 项随机试验、11,177 名参与者，比较多种非药物干预对焦虑、抑郁和生活质量的影响。摘要报告部分干预与短期症状改善相关，但生活质量证据不确定。',caveat:'网络排名受研究异质性、间接比较和头对头研究稀少影响；作者也建议结合可行性和患者偏好理解结果。',url:'https://pubmed.ncbi.nlm.nih.gov/42081951/'},
  {id:'chatbots-youth',pmid:'39935147',year:'2025',journal:'Expert Review of Medical Devices',topic:'数字心理干预',type:'随机试验荟萃分析',title:'心理健康聊天机器人，对抑郁和焦虑的证据一样吗？',paperTitle:'Effectiveness of mental health chatbots in depression and anxiety for adolescents and young adults',desc:'荟萃分析纳入 10 项面向青少年和年轻成人的随机试验，研究对象以女性和大学生为主。摘要报告抑郁症状有改善信号，但焦虑结局没有显著差异。',caveat:'样本构成偏窄，试验中的聊天机器人和对照差异较大；不能外推到所有年龄、诊断或商业聊天机器人。',url:'https://pubmed.ncbi.nlm.nih.gov/39935147/'}
];
