// Editorial learning samples, not summaries of actual studies. Translations are prepared locally.
const englishLessons = [
 {title:'Learning is more than recognising the answer',topic:'Learning & memory',paragraphs:[
 ['Imagine seeing a familiar face but being unable to remember the person’s name. Recognition and recall describe different ways of accessing memory: recognising something as familiar is different from producing information without seeing it.', '想象一下，你看到一张熟悉的面孔，却想不起对方的名字。再认和回忆描述的是不同的记忆提取方式：辨认某事物是否熟悉，与在未看到答案时主动提取信息并不相同。'],
 ['Here is a small language-learning exercise. Read a term and its meaning, cover the definition, and try to explain it in your own words. This asks you to retrieve the meaning rather than simply recognise the written definition.', '这里有一个语言学习小练习。读一个术语及其含义，遮住定义，再尝试用自己的话解释。这个过程要求你提取词义，而不只是认出写在眼前的定义。'],
 ['Then check your answer. Use feedback to notice what is missing or inaccurate. The aim is not to produce a perfect sentence immediately, but to make your understanding visible and revise it.', '接着核对答案，利用反馈发现遗漏或不准确之处。目标不是立刻说出完美的句子，而是把你的理解表达出来，再加以修正。'] ],terms:[
 ['recognition','再认','Identifying previously encountered information when it is presented again.','Recognition is different from recall.','再认与回忆不同。'],
 ['recall','回忆','Producing previously learned information rather than only identifying it when shown.','Try to recall the meaning without looking.','试着不看提示，回忆这个词的含义。'],
 ['memory','记忆','Processes involved in encoding, retaining, and retrieving information.','This task asks us to think about memory.','这个任务让我们思考记忆。'],
 ['retrieve','提取；检索','To bring stored information back into use or awareness.','Can you retrieve the word you learned yesterday?','你能想起昨天学过的那个词吗？'],
 ['feedback','反馈','Information about a response or performance that can guide revision.','Use the feedback to revise your explanation.','利用反馈修改你的解释。'],
 ['inaccurate','不准确的','Not correct or exact.','Part of my definition was inaccurate.','我的定义中有一部分不准确。'] ],quiz:{question:'Which example best illustrates recall?',options:['Recognising a term in a list.','Explaining a term without seeing its definition.','Copying a definition from a page.'],answer:1,explanation:'Recall involves producing information from memory. In this example, the definition is not in view.'}},
 {title:'A behaviour is not the same as an explanation',topic:'Behaviour & context',paragraphs:[
 ['A person stays quiet during a group discussion. That is an observation. Saying that the person is uninterested is an interpretation. The behaviour is visible, but its meaning still needs to be explored.', '一个人在小组讨论时保持沉默，这是观察。说这个人不感兴趣，则是一种解释。行为可以被看到，但它的含义仍需要探索。'],
 ['Context can change the questions we ask. Is the topic unfamiliar? Is the person waiting for a turn to speak? Generating more than one hypothesis helps us keep an observation separate from a possible explanation.', '情境会改变我们提出的问题。是不是话题不熟悉？是不是对方在等待发言机会？提出不止一种假设，有助于区分观察到的事实和可能的解释。'],
 ['In professional English, tentative language can make this distinction clear. Compare “This proves that…” with “This may suggest that…”. The second expression signals uncertainty; the strength of the wording should match the evidence.', '在专业英语中，审慎的表达可以明确这种区别。比较“This proves that…”（这证明了……）和“This may suggest that…”（这可能提示……）。后者表达了不确定性；措辞的强度应与证据相匹配。'] ],terms:[
 ['observation','观察；观察到的现象','Something noticed or recorded, distinguished here from an explanation of it.','Separate observation from interpretation.','将观察与解释区分开。'],
 ['interpretation','解释；解读','An account of what something means.','That is one possible interpretation.','那是一种可能的解释。'],
 ['behaviour','行为','What a person or other organism does; “behavior” is the US spelling.','Describe the behaviour before explaining it.','在解释行为之前，先描述行为。'],
 ['context','情境；背景','The circumstances in which something occurs.','Consider the social context.','考虑社会情境。'],
 ['hypothesis','假设','A proposed explanation or prediction that can be examined.','We need evidence to evaluate this hypothesis.','我们需要证据来评估这一假设。'],
 ['uncertainty','不确定性','A lack of complete certainty about a claim or result.','The wording should reflect uncertainty.','措辞应体现不确定性。'] ],quiz:{question:'Which sentence describes an observation rather than an interpretation?',options:['She did not speak during the discussion.','She had no interest in the topic.','She wanted the discussion to end.'],answer:0,explanation:'The first sentence describes an observable behaviour. The other two infer a motive or internal state.'}}
];
const psychBriefs = [
 {title:'Why sleep is a clinical signal, not just a symptom',topic:'Clinical perspective',text:'Sleep changes can appear across several mental-health conditions. A useful clinical question is not only “How many hours?” but also “What changed, when did it change, and how does it affect daytime functioning?”',zh:'睡眠变化可能出现在多种心理健康问题中。一个有用的临床问题不只是“睡了几小时”，还包括“发生了什么变化、何时开始变化，以及它如何影响白天的功能？”'},
 {title:'A transdiagnostic way to think about emotion',topic:'Concept in context',text:'Some psychological processes cut across diagnostic categories. Emotion regulation is one example: the same process may be relevant when a person presents with anxiety, depression, or stress-related difficulties.',zh:'有些心理过程会跨越不同诊断类别。情绪调节就是一个例子：当一个人表现出焦虑、抑郁或压力相关困难时，同一过程可能都具有相关性。'},
 {title:'What makes a finding clinically useful?',topic:'Evidence literacy',text:'A statistically reliable result is a starting point, not the end of the conversation. Clinicians also ask about the size of the effect, the population studied, the comparison condition, and whether the outcome matters to patients.',zh:'一个具有统计可靠性的结果只是讨论的起点。临床医生还会关注效应大小、研究人群、对照条件，以及这个结局是否对患者真正重要。'}
];
let englishLessonIndex=0;
const escapeEnglish=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderEnglish(){
 const l=englishLessons[englishLessonIndex];document.title='English Studio · Sophia';
 const section=location.hash.split('/')[1];if(section==='words'){renderWordBank();return}if(section==='practice'){renderPractice();return}
 app.innerHTML=`<section class="english-page" lang="en"><div class="page-title"><div class="eyebrow">A LITTLE ENGLISH, EVERY ISSUE</div><h1>Read psychology in English</h1><p>Short psychology briefs first, language practice inside the reading.</p></div><section class="briefs"><div class="section-head"><h2>Psychology in brief</h2><small>New ideas to read and discuss</small></div><div class="brief-grid">${psychBriefs.map(b=>`<article class="brief-card"><span class="tag">${b.topic}</span><h3>${b.title}</h3><p>${b.text}</p><details><summary>Show Chinese overview</summary><p lang="zh-CN">${b.zh}</p></details></article>`).join('')}</div></section><div class="section-head"><h2>Learn through a lesson</h2><small>Read, reveal, practise</small></div><div class="notice">Original learning lessons · Written for English practice, separate from the Chinese research journal. These are introductory concept lessons, not reviews of new studies.</div><div class="filters english-tabs" aria-label="Choose a reading topic">${englishLessons.map((x,i)=>`<button class="filter ${i===englishLessonIndex?'active':''}" data-lesson="${i}" aria-pressed="${i===englishLessonIndex}">${x.topic}</button>`).join('')}</div><div class="english-layout"><article class="english-reading"><span class="tag">Guided reading · Intermediate</span><h2>${l.title}</h2><div class="meta">3 short paragraphs · 6 words · 1 comprehension question</div><p class="english-hint">Underlined terms link to the vocabulary notes. Chinese stays hidden until you choose to reveal it.</p><button class="save" id="all-translations" aria-expanded="false">Show all Chinese translations</button>${l.paragraphs.map((p,i)=>`<section class="reading-block"><span class="paragraph-number">0${i+1}</span><p>${highlightTerms(p[0],l.terms)}</p><button class="translation-toggle" data-translate="${i}" aria-expanded="false" aria-controls="translation-${i}">Show Chinese translation</button><p class="translation" id="translation-${i}" lang="zh-CN" hidden>${p[1]}</p></section>`).join('')}<a class="primary practice-link" href="#english/practice">Practise this lesson</a></article><aside class="vocabulary"><div class="eyebrow">WORDS TO KEEP</div><h2>Vocabulary in context</h2><p class="english-hint">Open a term for its meaning and an example.</p>${l.terms.map((t,i)=>`<details class="term-card" id="term-${i}"><summary>${t[0]}</summary><div class="term-body"><strong lang="zh-CN">${t[1]}</strong><p>${t[2]}</p><span class="example-label">EXAMPLE</span><p class="example">${t[3]}</p><details class="example-translation"><summary>Show Chinese</summary><p lang="zh-CN">${t[4]}</p></details></div></details>`).join('')}</aside></div></section>`;
}
function highlightTerms(text,terms){let result=escapeEnglish(text);const pattern=new RegExp('\\b('+terms.map(t=>t[0].replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).sort((a,b)=>b.length-a.length).join('|')+')\\b','gi');return result.replace(pattern,m=>{const i=terms.findIndex(t=>t[0].toLowerCase()===m.toLowerCase());return `<button class="inline-term" data-term="${i}" aria-controls="term-${i}">${m}</button>`})}
function syncTranslations(){const all=[...document.querySelectorAll('[data-translate]')].every(b=>b.getAttribute('aria-expanded')==='true');const b=document.getElementById('all-translations');b.setAttribute('aria-expanded',String(all));b.textContent=all?'Hide all Chinese translations':'Show all Chinese translations'}
document.addEventListener('click',e=>{
 const lesson=e.target.closest('[data-lesson]');if(lesson){englishLessonIndex=Number(lesson.dataset.lesson);renderEnglish();return}
 const term=e.target.closest('[data-term]');if(term){const detail=document.getElementById('term-'+term.dataset.term);detail.open=true;detail.scrollIntoView({block:'nearest'});detail.querySelector('summary').focus();return}
 const b=e.target.closest('[data-translate]');if(b){const shown=b.getAttribute('aria-expanded')!=='true';document.getElementById(b.getAttribute('aria-controls')).hidden=!shown;b.setAttribute('aria-expanded',String(shown));b.textContent=shown?'Hide Chinese translation':'Show Chinese translation';syncTranslations();return}
 if(e.target.closest('#all-translations')){const shown=document.getElementById('all-translations').getAttribute('aria-expanded')!=='true';document.querySelectorAll('[data-translate]').forEach(b=>{document.getElementById(b.getAttribute('aria-controls')).hidden=!shown;b.setAttribute('aria-expanded',String(shown));b.textContent=shown?'Hide Chinese translation':'Show Chinese translation'});syncTranslations()}
});

function renderWordBank(){
 app.innerHTML=`<section class="english-page" lang="en"><div class="page-title"><div class="eyebrow">WORDS WITH A CONTEXT</div><h1>Your word bank</h1><p>Revisit the language from these lessons. Open a card when you need a hint.</p></div>${englishLessons.map(l=>`<h2>${l.topic}</h2><div class="word-grid">${l.terms.map(t=>`<details class="term-card"><summary>${t[0]}</summary><div class="term-body"><strong lang="zh-CN">${t[1]}</strong><p>${t[2]}</p><span class="example-label">EXAMPLE</span><p>${t[3]}</p><details class="example-translation"><summary>Show Chinese</summary><p lang="zh-CN">${t[4]}</p></details></div></details>`).join('')}</div>`).join('')}</section>`;
}
function renderPractice(){
 app.innerHTML=`<section class="english-page" lang="en"><div class="page-title"><div class="eyebrow">PAUSE. REMEMBER. TRY.</div><h1>A little practice</h1><p>Check the idea, then explain it in your own words.</p></div><div class="practice-grid">${englishLessons.map((l,i)=>`<article class="practice-card"><span class="tag">${l.topic}</span><h2>${l.quiz.question}</h2><fieldset><legend>Choose one answer</legend>${l.quiz.options.map((o,j)=>`<label><input type="radio" name="quiz-${i}" value="${j}"> ${o}</label>`).join('')}</fieldset><button class="primary" data-check="${i}">Check answer</button><p class="quiz-feedback" id="feedback-${i}" role="status"></p><details><summary>Try saying it aloud</summary><p>Explain “${l.terms[0][0]}” in one sentence, then use it in your own example.</p><p class="english-hint">Use the word bank to check your explanation. This exercise is for self-practice.</p></details></article>`).join('')}</div></section>`;
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-check]');if(!b)return;const i=Number(b.dataset.check);const choice=document.querySelector('input[name="quiz-'+i+'"]:checked');const feedback=document.getElementById('feedback-'+i);feedback.textContent=choice?((Number(choice.value)===englishLessons[i].quiz.answer?'Correct. ':'Not quite. ')+englishLessons[i].quiz.explanation):'Choose an answer first.';});
